### ISSUE TITLE
Good / bad connection

### ISSUE THREAD

**Issue by tangyan** [yandex/ozo#279] opened 2021-01-21 23:22 UTC
I noticed that it seems to be a bit hard to interpret what it means for a bad vs a good connection.  This affects how we reuse connection and connection pool.

The codes below showed the interesting part.

The line 15 uses a fake port to connect to postgres.  The line 16 is an invalid database uri.

The codes intentionally didn't write commit() because anyway it will always fail.  It tries to start a transaction, and because the database is not there, it will certainly fail.  Then in the begin() callback, we rollback the transaction.  This rollback certainly will also fail (which is fine), but it will still have the rollback callback.  In that callback, I check the connection status.

It turns out that if we use line 15, the connection status is always Not Bad.  If we use line 16, it is indeed bad.

The same thing happens even if we don't use connection pool.  If we just open a simple connection, it is the same behavior.  This seems to tell that we cannot be based on connection status to decide if the connection is healthy (to reuse) or not.

```
   1 #include <boost/asio/io_service.hpp>
   2 #include <ozo/transaction.h>
   3 #include <ozo/connection_info.h>
   4 #include <ozo/connection_pool.h>
   5 #include <boost/asio.hpp>
   6 #include <boost/bind.hpp>
   7 #include <boost/date_time/posix_time/posix_time.hpp>
   8
   9 namespace asio = boost::asio;
  10
  11 using ConnectionPool = ozo::connection_pool<ozo::connection_info<>>;
  12 using Connection = ozo::connection_provider<ConnectionPool>::connection_type;
  13 using Transaction = ozo::transaction<Connection, decltype(ozo::make_options())>;
  14                                                                                                                                                                       no type named 'connection_info' in namespace 'ozo' [2]
  15 ozo::connection_info conn_info("postgresql://postgres:postgres@localhost:1000/test");
  16 // ozo::connection_info conn_info("abc");
  17 ozo::connection_pool_config conn_pool_config{10, 10, std::chrono::seconds(60), std::chrono::hours(24)};
  18 ConnectionPool conn_pool(conn_info, conn_pool_config);
  19 asio::io_context io;
  20
  21 void InTrans(const ozo::error_code& ec, Transaction tran) {
  22     if (ec) {
  23         std::cout << ec.message().c_str() << std::endl;
  24         std::cout << "Start to rollback" << std::endl;
  25         ozo::rollback(std::move(tran), [](ozo::error_code /*ec*/, Connection connection) {
  26             if (connection->is_bad()) {
  27                 std::cout << "is bad" << std::endl;
  28             } else {
  29                 std::cout << "is good" << std::endl;
  30             }
  31         });
  32     }
  33     std::cout << "in trans" << std::endl;
  34 }
  35
  36 void test() {
  37     using namespace std::chrono_literals;
  38     for (int i = 0; i < 2; ++i) {
  39         std::cout << "hello" << std::endl;
  40         ozo::begin(conn_pool[io], 3s, [](ozo::error_code ec, Transaction tran) {
  41             InTrans(ec, std::move(tran));
  42         });
  43     }
  44 }
  45
  46 int main() {
  47     test();
  48     io.run();
  49     return 0;
  50 }
```

Use line 15:
```
hello
hello
Connection timed out
Start to rollback
is good
in trans
Connection timed out
Start to rollback
is good
in trans
```

Use line 16:
```
hello
hello
pq_connection_status_bad - PQstatus returned CONNECTION_BAD
Start to rollback
is bad
in trans
pq_connection_status_bad - PQstatus returned CONNECTION_BAD
Start to rollback
is bad
in trans
```

**Comment by thed636** [comment] 2021-01-24 17:29
Hi @tangyan !

Could you please check this [topic about error handling](https://github.com/yandex/ozo/blob/master/docs/howto.md#how-to-handle-error-properly) of the How-To. In case of error, the connection should be checked for the null state, since this is a nullable object. You may find useful the [ozo::connection_bad()](https://yandex.github.io/ozo/group__group-connection-functions.html#gaf6f38bd0e9211b1676a6ef05fa5e24f5) function that examines the connection for a null state. So as its sibling convenience function `ozo::connection_good()`.

Hope that helps.

**Comment by tangyan** [comment] 2021-01-24 19:30
I've read the topic about error handling in the How-To.  However, it doesn't address my question.

You can directly copy and paste the above test codes and see what it actually happens.  I didn't check the ec code is mainly to show/expose the issue.

The issue is that when there is an error (especially when the connection fails), after rollback, the ec errorcode indeed returns error and I can print the error message.

But when check the connection_bad(), it returns false, which indicates the connection is good.  This is impossible because as I showed in the test codes above, the db is not up so the connection cannot be good, :).

**Comment by thed636** [comment] 2021-01-24 19:47
A-ha. I see then. Thanx for clarifying. It is strange because that means the underlying libpq function `PQstatus()` returns a connection status different from `CONNECTION_BAD`. The `libpq` documentation says `A failed connection attempt is signaled by status CONNECTION_BAD.`. So maybe the problem is because of time-out which is not a part of `libpq` and it should be handled with additional logic. Could you please provide more information about `libpq` version you are using?

**Comment by tangyan** [comment] 2021-01-25 23:15
The version we use seems to be:

libpq.so.5 => /usr/pgsql-12/lib/libpq.so.5 (0x00007f4774e20000)

I indeed looked at the ozo codes and I think it gets the connection status from PGStatus?

**Comment by thed636** [comment] 2021-02-02 15:22
> I indeed looked at the ozo codes and I think it gets the connection status from PGStatus?

Yep, and this is the problem. Looks like a comparison with the `CONNECTION_BAD`isn't the right choice since there are additional states except the `CONNECTION_BAD` and `CONNECTION_OK`. During the connection time-out, the function returns `CONNECTION_STARTED` (thanks to @elsid for this little investigation). In our case, it looks like we need to change the behaviour and compare the state with `CONNECTION_OK ` since the other states should not be achieved by the library user in normal cases between operations. Sorry, I have not enough time to fix it right now, but I think we will fix it in the nearest future. 

Thanks for the report! This obscured bug may mislead users in a very unpleasant way.

**Comment by tangyan** [comment] 2021-02-06 03:40
Thank you and thanks for writing the library!

**Comment by thed636** [comment] 2021-02-19 07:22
@tangyan you are welcome!

The fix has been merged.

**Closed as completed by thed636** 2021-02-19 07:22 UTC
Labels: bug
